# Generated by Django 4.2.16 on 2026-04-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_checkin_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='checkin_type',
            field=models.CharField(choices=[('food', 'Alimentação'), ('walk', 'Passeio'), ('vet', 'Veterinário'), ('medication', 'Medicação'), ('vacine', 'Vacinação'), ('other', 'Outros')], max_length=20),
        ),
    ]
